name: Publish To Technologic Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Build Env
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install 18.14.2
          nvm use 18.14.2

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run-script build

      - name: Copying to technologic.xpress.ai
        run: rsync -r -v build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/technologic.xpress.ai/
