name: Publish To Technologic Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run build

      - name: Copying to technologic.xpress.ai
        run: rsync -r -v build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/technologic.xpress.ai/
